name: showcase_demo
description: A Flutter project to manage onboarding.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  showcaseview: ^1.1.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/

flutter:
  uses-material-design: true
  assets:
    - assets/json/
